[package]
name = "cli-rcsplit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
memmap2 = "0.9"
rayon = "1.8"
regex-automata = "0.4"
crossbeam-channel = "0.5"  # New dependency for streaming processing
