[package]
name = "rst"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
fs4 = "0.13.1"
indicatif = "0.17.11"
memmap2 = "0.9"
num_cpus = "1.16"
rayon = "1.10"
regex-automata = "0.4"
memchr = "2.7"
